# Generated by Django 5.2.5 on 2025-08-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='about/')),
                ('hero_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
