# Generated by Django 5.2.5 on 2025-08-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_application_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='view_count',
        ),
    ]
