# Generated by Django 5.2.5 on 2025-09-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_subcategory_category_category_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='main_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='applicationimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_image',
            field=models.ImageField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='applicationimage',
            name='image',
            field=models.ImageField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='temp/'),
        ),
    ]
