# Generated by Django 5.2.5 on 2025-12-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_application_denied_reason_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('theme', models.CharField(choices=[('Ehson haqida', 'Ehson haqida'), ('Hamkorlik', 'Hamkorlik'), ('Texnik masala', 'Texnik masala'), ('Boshqa', 'Boshqa')], max_length=50)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AddField(
            model_name='application',
            name='document_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AddField(
            model_name='application',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent'), ('Samarqand', 'Samarqand'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Jizzax', 'Jizzax'), ('Sirdaryo', 'Sirdaryo'), ('Xorazm', 'Xorazm'), ('Navoiy', 'Navoiy'), ("Qoraqalpog'iston", "Qoraqalpog'iston")], max_length=100),
        ),
    ]
