# Generated by Django 5.2.5 on 2025-12-23 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_banner_contactus_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationimage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
